# Generated by Django 3.0.6 on 2020-06-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200617_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_uploaded'],
            },
        ),
        migrations.AddField(
            model_name='spend',
            name='spend_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.SpendUpload'),
            preserve_default=False,
        ),
    ]
