# Generated by Django 3.0.6 on 2020-06-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200622_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='spend_upload',
            new_name='upload_record',
        ),
        migrations.AddField(
            model_name='spendupload',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.Platform'),
            preserve_default=False,
        ),
    ]
