# Generated by Django 3.0.6 on 2020-06-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200622_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpendUpload',
            new_name='SpendUploadRecord',
        ),
    ]
