# Generated by Django 3.0.6 on 2020-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200622_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='platforms',
        ),
        migrations.AddField(
            model_name='campaign',
            name='platforms',
            field=models.ManyToManyField(to='clients.Platform'),
        ),
    ]
