# Generated by Django 3.0.7 on 2020-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20200623_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(),
        ),
    ]
